const initState = {
    posts: [
        {id: '1', title: 'Tree', body: 'In botany, a tree is a perennial plant with an elongated stem, or trunk, supporting branches and leaves in most species. In some usages, the definition of a tree may be narrower, including only woody plants with secondary growth, plants that are usable as lumber or plants above a specified height. Trees are not a taxonomic group but include a variety of plant species that have independently evolved a woody trunk and branches as a way to tower above other plants to compete for sunlight. Trees tend to be long-lived, some reaching several thousand years old. In wider definitions, the taller palms, tree ferns, bananas, and bamboos are also trees. Trees have been in existence for 370 million years. It is estimated that there are just over 3 trillion mature trees in the world.[1]A tree typically has many secondary branches supported clear of the ground by the trunk. This trunk typically contains woody tissue for strength, and vascular tissue to carry materials from one part of the tree to another. For most trees it is surrounded by a layer of bark which serves as a protective barrier. Below the ground, the roots branch and spread out widely; they serve to anchor the tree and extract moisture and nutrients from the soil. Above ground, the branches divide into smaller branches and shoots. The shoots typically bear leaves, which capture light energy and convert it into sugars by photosynthesis, providing the food for the trees growth and development. '},
        {id: '2', title: 'Squirrel', body: 'Squirrels are generally small animals, ranging in size from the African pygmy squirrel at 7–10 cm (2.8–3.9 in) in length and just 10 g (0.35 oz) in weight, to the Laotian giant flying squirrel at 1.08 m (3 ft 7 in) in length and the Alpine marmot, which weighs from 5 to 8 kg (11 to 18 lb). Squirrels typically have slender bodies with bushy tails and large eyes. In general, their fur is soft and silky, though much thicker in some species than others. The coat color of squirrels is highly variable between—and often even within—species.[5] In most squirrel species, the hind limbs are longer than the fore limbs, while all species have either four or five toes on each paw. The paws, which include an often poorly developed thumb, have soft pads on the undersides[6] and versatile, sturdy claws for grasping and climbing.[7] Tree squirrels, unlike most mammals, can descend a tree head-first. They do so by rotating their ankles 180 degrees, enabling the hind paws to point backward and thus grip the tree bark from the opposite direction.[8] Squirrels live in almost every habitat, from tropical rainforest to semiarid desert, avoiding only the high polar regions and the driest of deserts. They are predominantly herbivorous, subsisting on seeds and nuts, but many will eat insects and even small vertebrates.[9] As their large eyes indicate, squirrels have an excellent sense of vision, which is especially important for the tree-dwelling species. Many also have a good sense of touch, with vibrissae on their limbs as well as their heads.[6] The teeth of sciurids follow the typical rodent pattern, with large incisors (for gnawing) that grow throughout life, and cheek teeth (for grinding) that are set back behind a wide gap, or diastema. The typical dental formula for sciurids is 1.0.1.31.0.1.3.[10]Many juvenile squirrels die in the first year of life. Adult squirrels can have a lifespan of 5 to 10 years in the wild. Some can survive 10 to 20 years in captivity.[11] Premature death may be caused when a nest falls from the tree, in which case the mother may abandon her young if their body temperature is not correct. Many such baby squirrels have been rescued and fostered by a professional wildlife rehabilitator until they could be safely returned to the wild,[12] although the density of squirrel populations in many places and the constant care required by premature squirrels means that few rehabilitators are willing to spend their time doing this and such animals are routinely euthanized instead. '},
        {id: '3', title: 'Dogs', body: 'The domestic dog (Canis lupus familiaris when considered a subspecies of the wolf or Canis familiaris when considered a distinct species)[5] is a member of the genus Canis (canines), which forms part of the wolf-like canids,[6] and is the most widely abundant terrestrial carnivore.[7][8][9][10][11] The dog and the extant gray wolf are sister taxa[12][13][14] as modern wolves are not closely related to the wolves that were first domesticated,[13][14] which implies that the direct ancestor of the dog is extinct.[15] The dog was the first species to be domesticated[14][16] and has been selectively bred over millennia for various behaviors, sensory capabilities, and physical attributes.[17] Their long association with humans has led dogs to be uniquely attuned to human behavior[18] and they are able to thrive on a starch-rich diet that would be inadequate for other canid species.[19] Dogs vary widely in shape, size and colors.[20] They perform many roles for humans, such as hunting, herding, pulling loads, protection, assisting police and military, companionship and, more recently, aiding disabled people and therapeutic roles. This influence on human society has given them the sobriquet of "mans best friend".'}
    ]
}
const rootReducer = (state = initState, action) => {
    return state;
    
}
export default rootReducer